export const Templates = [
  {
    name: "Resturant Campaign",
    image: "/resturant.png",
    components: [
      {
        id: "header-image",
        type: "image",
        data: {
          src: "https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg?auto=compress&cs=tinysrgb&h=350",
          alt: "Delicious spread of restaurant dishes",
          width: "50%",
          height: "300px",
        },
      },
      {
        id: "welcome-heading",
        type: "heading",
        data: {
          content: "Welcome to Our Culinary Journey!",
          level: "h1",
          color: "#333333",
          alignment: "center",
          font: "Verdana",
          bold: true,
          italic: false,
          underline: false,
        },
      },
      {
        id: "intro-text",
        type: "text-block",
        data: {
          content:
            "Discover a symphony of flavors crafted with passion and the finest ingredients. We invite you to explore our exquisite menu, designed to delight your senses.",
          fontSize: "16px",
          font: "Arial",
          color: "#555555",
          alignment: "center",
          bold: false,
          italic: false,
          underline: false,
        },
      },
      {
        id: "menu-divider-1",
        type: "divider",
        data: { style: "solid", color: "#DDDDDD", height: "2px" },
      },
      {
        id: "menu-sections-heading",
        type: "heading",
        data: {
          content: "Featured Menu Items",
          level: "h2",
          color: "#333333",
          alignment: "left",
          font: "Verdana",
          bold: true,
          italic: false,
          underline: false,
        },
      },
      {
        id: "menu-columns",
        type: "column",
        data: {
          width: "100%",
          backgroundColor: "#FFFFFF",
          padding: "20px",
          gap: "30px",
          columns: 3,
          columnsData: [
            [
              {
                id: "appetizer-image",
                type: "image",
                data: {
                  src: "https://www.ourhomemadeeasy.com/wp-content/uploads/2025/07/Easy-Meat-Cheese-Appetizer-Featured-Image-720x720.png",
                  alt: "Gourmet appetizer",
                  width: "100%",
                  height: "200px",
                  pexelsQuery: "appetizer food",
                },
              },
              {
                id: "appetizer-heading",
                type: "heading",
                data: {
                  content: "Appetizers",
                  level: "h3",
                  color: "#333333",
                  alignment: "center",
                  font: "Georgia",
                  bold: true,
                  italic: false,
                  underline: false,
                },
              },
              {
                id: "appetizer-text",
                type: "text-block",
                data: {
                  content:
                    "Start your meal with our delightful selection of small plates, from crispy calamari to fresh bruschetta.",
                  fontSize: "14px",
                  font: "Arial",
                  color: "#666666",
                  alignment: "center",
                  bold: false,
                  italic: false,
                  underline: false,
                },
              },
            ],
            [
              {
                id: "main-course-image",
                type: "image",
                data: {
                  src: "https://www.foodandwine.com/thmb/MT-PmMm_-6BVcPl8tbcnybIf7Vk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/reverse-sear-steak-FT-RECIPE0222-5c6f8d9a037a4ca2b170adea0529ba7a.jpg",
                  alt: "Juicy steak main course",
                  width: "100%",
                  height: "200px",
                  pexelsQuery: "steak dinner",
                },
              },
              {
                id: "main-course-heading",
                type: "heading",
                data: {
                  content: "Main Courses",
                  level: "h3",
                  color: "#333333",
                  alignment: "center",
                  font: "Georgia",
                  bold: true,
                  italic: false,
                  underline: false,
                },
              },
              {
                id: "main-course-text",
                type: "text-block",
                data: {
                  content:
                    "Savor our expertly prepared main courses, featuring succulent meats, fresh seafood, and vibrant vegetarian options.",
                  fontSize: "14px",
                  font: "Arial",
                  color: "#666666",
                  alignment: "center",
                  bold: false,
                  italic: false,
                  underline: false,
                },
              },
            ],
            [
              {
                id: "dessert-image",
                type: "image",
                data: {
                  src: "https://www.modernhoney.com/wp-content/uploads/2024/01/Best-Chocolate-Cake-2-crop-scaled.jpg",
                  alt: "Decadent chocolate cake dessert",
                  width: "100%",
                  height: "200px",
                  pexelsQuery: "chocolate cake dessert",
                },
              },
              {
                id: "dessert-heading",
                type: "heading",
                data: {
                  content: "Desserts",
                  level: "h3",
                  color: "#333333",
                  alignment: "center",
                  font: "Georgia",
                  bold: true,
                  italic: false,
                  underline: false,
                },
              },
              {
                id: "dessert-text",
                type: "text-block",
                data: {
                  content:
                    "Indulge your sweet tooth with our decadent desserts, from rich chocolate lava cake to refreshing fruit tarts.",
                  fontSize: "14px",
                  font: "Arial",
                  color: "#666666",
                  alignment: "center",
                  bold: false,
                  italic: false,
                  underline: false,
                },
              },
            ],
          ],
        },
      },
      {
        id: "view-full-menu-button",
        type: "button",
        data: {
          text: "View Full Menu",
          url: "#",
          backgroundColor: "#FF6347",
          color: "#FFFFFF",
          padding: "16px 32px",
          borderRadius: "8px",
        },
      },
      { id: "spacer-after-button", type: "spacer", data: { height: "40px" } },
      {
        id: "special-offer-heading",
        type: "heading",
        data: {
          content: "Special Offer This Week!",
          level: "h2",
          color: "#333333",
          alignment: "center",
          font: "Verdana",
          bold: true,
          italic: false,
          underline: false,
        },
      },
      {
        id: "special-offer-image",
        type: "image",
        data: {
          src: "https://images.pexels.com/photos/10432634/pexels-photo-10432634.jpeg?auto=compress&cs=tinysrgb&h=350",
          alt: "Chef preparing a special dish",
          width: "50%",
          height: "300px",
        },
      },
      {
        id: "special-offer-text",
        type: "text-block",
        data: {
          content:
            "Enjoy 15% off our Chef's Signature Pasta Dish every Wednesday! Mention this email to redeem your offer.",
          fontSize: "18px",
          font: "Arial",
          color: "#555555",
          alignment: "center",
          bold: true,
          italic: false,
          underline: false,
        },
      },
      {
        id: "reservation-button",
        type: "button",
        data: {
          text: "Make a Reservation",
          url: "#",
          backgroundColor: "#4682B4",
          color: "#FFFFFF",
          padding: "16px 32px",
          borderRadius: "8px",
        },
      },
      {
        id: "footer-divider",
        type: "divider",
        data: { style: "dotted", color: "#CCCCCC", height: "1px" },
      },
      {
        id: "social-media-links",
        type: "social-media",
        data: {
          platforms: [
            { name: "facebook", url: "#" },
            { name: "instagram", url: "#" },
            { name: "twitter", url: "#" },
          ],
          iconSize: "32px",
          color: "#555555",
          alignment: "center",
        },
      },
      {
        id: "footer-text",
        type: "text-block",
        data: {
          content:
            "© 2023 Restaurant Name. All rights reserved. 123 Culinary Lane, Foodville, CA 90210",
          fontSize: "12px",
          font: "Arial",
          color: "#888888",
          alignment: "center",
          bold: false,
          italic: false,
          underline: false,
        },
      },
      {
        id: "unsubscribe-link",
        type: "link",
        data: {
          text: "Unsubscribe",
          url: "#",
          color: "#888888",
          underline: true,
          alignment: "center",
        },
      },
    ],
  },
  {
    name: "Welcome Email",
    image: "/welcome.png",
    components: [
      {
        id: "header-logo",
        type: "image",
        data: {
          src: "https://static.vecteezy.com/system/resources/previews/008/214/517/non_2x/abstract-geometric-logo-or-infinity-line-logo-for-your-company-free-vector.jpg",
          alt: "Company Logo",
          width: "150px",
          height: "auto",
        },
      },
      {
        id: "welcome-heading",
        type: "heading",
        data: {
          content: "Welcome to Our Community!",
          level: "h1",
          color: "#333333",
          alignment: "center",
          font: "Verdana",
          bold: true,
          italic: false,
          underline: false,
        },
      },
      { id: "welcome-spacer-1", type: "spacer", data: { height: "30px" } },
      {
        id: "welcome-image",
        type: "image",
        data: {
          src: "https://images.pexels.com/photos/8088500/pexels-photo-8088500.jpeg?auto=compress&cs=tinysrgb&h=350",
          alt: "Illustration of people connecting",
          width: "50%",
          height: "auto",
        },
      },
      {
        id: "welcome-text",
        type: "text-block",
        data: {
          content:
            "We are thrilled to have you join our growing community. Get ready to discover new opportunities, connect with like-minded individuals, and unlock your potential. Explore our platform to get started!",
          fontSize: "16px",
          font: "Arial",
          color: "#555555",
          alignment: "center",
          bold: false,
          italic: false,
          underline: false,
        },
      },
      { id: "welcome-spacer-2", type: "spacer", data: { height: "30px" } },
      {
        id: "get-started-button",
        type: "button",
        data: {
          text: "Get Started Now",
          url: "https://example.com/get-started",
          backgroundColor: "#007bff",
          color: "#ffffff",
          padding: "16px 32px",
          borderRadius: "8px",
        },
      },
      {
        id: "welcome-divider",
        type: "divider",
        data: { style: "solid", color: "#eeeeee", height: "1px" },
      },
      { id: "welcome-spacer-3", type: "spacer", data: { height: "30px" } },
      {
        id: "helpful-resources-heading",
        type: "heading",
        data: {
          content: "Helpful Resources",
          level: "h3",
          color: "#333333",
          alignment: "left",
          font: "Verdana",
          bold: true,
          italic: false,
          underline: false,
        },
      },
      {
        id: "resources-columns",
        type: "column",
        data: {
          width: "100%",
          backgroundColor: "#ffffff",
          padding: "0px",
          gap: "20px",
          columns: 3,
          columnsData: [
            [
              {
                id: "resource-image-1",
                type: "image",
                data: {
                  src: "https://resources.careersandenterprise.co.uk/sites/default/files/2020-07/Group%201774.svg",
                  alt: "Guidebook icon",
                  width: "100%",
                  height: "150px",
                  pexelsQuery: "guidebook open",
                },
              },
              {
                id: "resource-heading-1",
                type: "heading",
                data: {
                  content: "Getting Started Guide",
                  level: "h4",
                  color: "#333333",
                  alignment: "center",
                  font: "Arial",
                  bold: true,
                  italic: false,
                  underline: false,
                },
              },
              {
                id: "resource-text-1",
                type: "text-block",
                data: {
                  content:
                    "Learn the basics and navigate our platform with ease.",
                  fontSize: "12px",
                  font: "Arial",
                  color: "#666666",
                  alignment: "center",
                  bold: false,
                  italic: false,
                  underline: false,
                },
              },
              {
                id: "resource-link-1",
                type: "link",
                data: {
                  text: "Read More",
                  url: "https://example.com/guide",
                  color: "#007bff",
                  underline: true,
                  alignment: "center",
                },
              },
            ],
            [
              {
                id: "resource-image-2",
                type: "image",
                data: {
                  src: "https://static.vecteezy.com/system/resources/thumbnails/005/887/265/small_2x/faq-illustration-on-a-background-premium-quality-symbols-icons-for-concept-or-graphic-design-vector.jpg",
                  alt: "FAQ icon",
                  width: "100%",
                  height: "150px",
                  pexelsQuery: "frequently asked questions document",
                },
              },
              {
                id: "resource-heading-2",
                type: "heading",
                data: {
                  content: "Frequently Asked Questions",
                  level: "h4",
                  color: "#333333",
                  alignment: "center",
                  font: "Arial",
                  bold: true,
                  italic: false,
                  underline: false,
                },
              },
              {
                id: "resource-text-2",
                type: "text-block",
                data: {
                  content: "Find answers to common questions.",
                  fontSize: "12px",
                  font: "Arial",
                  color: "#666666",
                  alignment: "center",
                  bold: false,
                  italic: false,
                  underline: false,
                },
              },
              {
                id: "resource-link-2",
                type: "link",
                data: {
                  text: "View FAQs",
                  url: "https://example.com/faq",
                  color: "#007bff",
                  underline: true,
                  alignment: "center",
                },
              },
            ],
            [
              {
                id: "resource-image-3",
                type: "image",
                data: {
                  src: "https://designshack.net/wp-content/uploads/tutorial-videos-youtube-thumbnail-501-1.jpg",
                  alt: "Tutorial icon",
                  width: "100%",
                  height: "150px",
                  pexelsQuery: "online course video",
                },
              },
              {
                id: "resource-heading-3",
                type: "heading",
                data: {
                  content: "Video Tutorials",
                  level: "h4",
                  color: "#333333",
                  alignment: "center",
                  font: "Arial",
                  bold: true,
                  italic: false,
                  underline: false,
                },
              },
              {
                id: "resource-text-3",
                type: "text-block",
                data: {
                  content: "Watch helpful videos to maximize your experience.",
                  fontSize: "12px",
                  font: "Arial",
                  color: "#666666",
                  alignment: "center",
                  bold: false,
                  italic: false,
                  underline: false,
                },
              },
              {
                id: "resource-link-3",
                type: "link",
                data: {
                  text: "Watch Now",
                  url: "https://example.com/tutorials",
                  color: "#007bff",
                  underline: true,
                  alignment: "center",
                },
              },
            ],
          ],
        },
      },
      { id: "welcome-spacer-4", type: "spacer", data: { height: "40px" } },
      {
        id: "footer-social-media",
        type: "social-media",
        data: {
          platforms: [
            { name: "facebook", url: "https://facebook.com/yourcompany" },
            { name: "twitter", url: "https://twitter.com/yourcompany" },
            { name: "linkedin", url: "https://linkedin.com/yourcompany" },
            { name: "instagram", url: "https://instagram.com/yourcompany" },
          ],
          iconSize: "32px",
          color: "#007bff",
          alignment: "center",
        },
      },
      {
        id: "footer-text",
        type: "text-block",
        data: {
          content:
            "© 2023 Your Company Name. All rights reserved. <br><a href='https://example.com/unsubscribe' style='color: #666666; text-decoration: underline;'>Unsubscribe</a>",
          fontSize: "12px",
          font: "Arial",
          color: "#666666",
          alignment: "center",
          bold: false,
          italic: false,
          underline: false,
        },
      },
    ],
  },
  {
    name: "Invitation",
    image: "/invitation.png",
    components: [
      {
        id: "header-logo",
        type: "image",
        data: {
          src: "https://static.vecteezy.com/system/resources/previews/008/214/517/non_2x/abstract-geometric-logo-or-infinity-line-logo-for-your-company-free-vector.jpg",
          alt: "Company Logo",
          width: "200px",
          height: "auto",
        },
      },
      {
        id: "main-heading",
        type: "heading",
        data: {
          content: "You're Invited!",
          level: "h1",
          color: "#333333",
          alignment: "center",
          font: "Verdana",
          bold: true,
          italic: false,
          underline: false,
        },
      },
      { id: "spacer-1", type: "spacer", data: { height: "30px" } },
      {
        id: "event-image",
        type: "image",
        data: {
          src: "https://images.pexels.com/photos/7414273/pexels-photo-7414273.jpeg?auto=compress&cs=tinysrgb&h=350",
          alt: "Event Photo",
          width: "50%",
          height: "300px",
        },
      },
      { id: "spacer-2", type: "spacer", data: { height: "40px" } },
      {
        id: "event-details-heading",
        type: "heading",
        data: {
          content: "Annual Tech Summit 2024",
          level: "h2",
          color: "#0056b3",
          alignment: "center",
          font: "Verdana",
          bold: true,
          italic: false,
          underline: false,
        },
      },
      {
        id: "event-date",
        type: "text-block",
        data: {
          content: "Date: October 26",
          fontSize: "16px",
          color: "#555555",
          alignment: "center",
          font: "Arial",
          bold: false,
          italic: false,
          underline: false,
        },
      },
      {
        id: "event-time",
        type: "text-block",
        data: {
          content: "Time: 9:00 AM - 5:00 PM PST",
          fontSize: "16px",
          color: "#555555",
          alignment: "center",
          font: "Arial",
          bold: false,
          italic: false,
          underline: false,
        },
      },
      {
        id: "event-location",
        type: "text-block",
        data: {
          content:
            "Venue: Grand Conference Center, 123 Innovation Drive, Techville, CA 94000",
          fontSize: "16px",
          font: "Arial",
          color: "#555555",
          alignment: "center",
          bold: false,
          italic: false,
          underline: false,
        },
      },
      { id: "spacer-3", type: "spacer", data: { height: "30px" } },
      {
        id: "description-heading",
        type: "heading",
        data: {
          content: "About the Event",
          level: "h3",
          color: "#333333",
          alignment: "left",
          font: "Verdana",
          bold: true,
          italic: false,
          underline: false,
        },
      },
      {
        id: "description-text",
        type: "text-block",
        data: {
          content:
            "Join us for our Annual Tech Summit, a premier event bringing together industry leaders, innovators, and enthusiasts to explore the latest trends and advancements in technology. This year, we'll be focusing on AI, sustainable tech, and the future of digital transformation.",
          fontSize: "14px",
          font: "Arial",
          color: "#444444",
          alignment: "left",
          bold: false,
          italic: false,
          underline: false,
        },
      },
      { id: "spacer-4", type: "spacer", data: { height: "30px" } },
      {
        id: "agenda-heading",
        type: "heading",
        data: {
          content: "Event Highlights",
          level: "h3",
          color: "#333333",
          alignment: "left",
          font: "Verdana",
          bold: true,
          italic: false,
          underline: false,
        },
      },
      {
        id: "column-layout-agenda",
        type: "column",
        data: {
          width: "100%",
          backgroundColor: "#ffffff",
          padding: "20px",
          gap: "20px",
          columns: 2,
          columnsData: [
            [
              {
                id: "agenda-item-1",
                type: "text-block",
                data: {
                  content: "Keynote Address by Dr. Evelyn Reed",
                  fontSize: "14px",
                  font: "Arial",
                  color: "#555555",
                  alignment: "left",
                  bold: true,
                  italic: false,
                  underline: false,
                },
              },
              {
                id: "agenda-item-1-detail",
                type: "text-block",
                data: {
                  content: "Insights into the future of AI.",
                  fontSize: "12px",
                  color: "#777777",
                  alignment: "left",
                  font: "Arial",
                  bold: false,
                  italic: true,
                  underline: false,
                },
              },
            ],
            [
              {
                id: "agenda-item-2",
                type: "text-block",
                data: {
                  content: "Panel Discussion: Sustainable Tech",
                  fontSize: "14px",
                  font: "Arial",
                  color: "#555555",
                  alignment: "left",
                  bold: true,
                  italic: false,
                  underline: false,
                },
              },
              {
                id: "agenda-item-2-detail",
                type: "text-block",
                data: {
                  content: "Exploring eco-friendly innovations.",
                  fontSize: "12px",
                  font: "Arial",
                  color: "#777777",
                  alignment: "left",
                  bold: false,
                  italic: true,
                  underline: false,
                },
              },
            ],
          ],
        },
      },
      { id: "spacer-5", type: "spacer", data: { height: "40px" } },
      {
        id: "cta-button",
        type: "button",
        data: {
          text: "RSVP Now",
          url: "https://example.com/rsvp",
          backgroundColor: "#007bff",
          color: "#ffffff",
          padding: "16px 32px",
          borderRadius: "8px",
        },
      },
      { id: "spacer-6", type: "spacer", data: { height: "50px" } },
      {
        id: "divider-1",
        type: "divider",
        data: { style: "solid", color: "#eeeeee", height: "1px" },
      },
      { id: "spacer-7", type: "spacer", data: { height: "30px" } },
      {
        id: "footer-text",
        type: "text-block",
        data: {
          content:
            "For more information, please visit our <link>website</link> or contact us at <link>info@example.com</link>.",
          fontSize: "12px",
          font: "Arial",
          color: "#888888",
          alignment: "center",
          bold: false,
          italic: false,
          underline: false,
        },
      },
      {
        id: "social-media-links",
        type: "social-media",
        data: {
          platforms: [
            {
              name: "linkedin",
              url: "https://www.linkedin.com/company/example",
            },
            { name: "twitter", url: "https://www.twitter.com/example" },
            { name: "instagram", url: "https://www.instagram.com/example" },
          ],
          iconSize: "24px",
          color: "#888888",
          alignment: "center",
        },
      },
      {
        id: "footer-copyright",
        type: "text-block",
        data: {
          content: "&copy; 2024 Example Company. All rights reserved.",
          fontSize: "10px",
          font: "Arial",
          color: "#aaaaaa",
          alignment: "center",
          bold: false,
          italic: false,
          underline: false,
        },
      },
    ],
  },
  {
    name: "Feedback",
    image: "/feedback.png",
    components: [
      {
        id: "header-logo",
        type: "image",
        data: {
          src: "https://images.pexels.com/photos/258174/pexels-photo-258174.jpeg?auto=compress&cs=tinysrgb&h=350",
          alt: "Company Logo",
          width: "200px",
          height: "auto",
        },
      },
      { id: "spacer-1", type: "spacer", data: { height: "30px" } },
      {
        id: "main-heading",
        type: "heading",
        data: {
          content: "We Value Your Feedback!",
          level: "h1",
          color: "#1a202c",
          alignment: "center",
          font: "Verdana",
          bold: true,
          italic: false,
          underline: false,
        },
      },
      { id: "spacer-2", type: "spacer", data: { height: "20px" } },
      {
        id: "intro-text",
        type: "text-block",
        data: {
          content:
            "Thank you for choosing [Your Company Name]. We are constantly striving to improve our products and services, and your feedback is invaluable to us. Please take a moment to share your experience.",
          fontSize: "16px",
          font: "Arial",
          color: "#4a5568",
          alignment: "center",
          bold: false,
          italic: false,
          underline: false,
        },
      },
      { id: "spacer-3", type: "spacer", data: { height: "30px" } },
      {
        id: "review-image",
        type: "image",
        data: {
          src: "https://images.pexels.com/photos/8866796/pexels-photo-8866796.jpeg?auto=compress&cs=tinysrgb&h=350",
          alt: "Customer Satisfaction",
          width: "50%",
          height: "auto",
        },
      },
      { id: "spacer-4", type: "spacer", data: { height: "30px" } },
      {
        id: "call-to-action-button",
        type: "button",
        data: {
          text: "Leave a Review",
          url: "YOUR_REVIEW_LINK_HERE",
          backgroundColor: "#3182ce",
          color: "#ffffff",
          padding: "12px 24px",
          borderRadius: "4px",
        },
      },
      { id: "spacer-5", type: "spacer", data: { height: "40px" } },
      {
        id: "divider-1",
        type: "divider",
        data: { style: "solid", color: "#e2e8f0", height: "1px" },
      },
      { id: "spacer-6", type: "spacer", data: { height: "30px" } },
      {
        id: "columns-section",
        type: "column",
        data: {
          width: "100%",
          backgroundColor: "#ffffff",
          padding: "20px",
          gap: "20px",
          columns: 2,
          columnsData: [
            [
              {
                id: "column1-heading",
                type: "heading",
                data: {
                  content: "Why Your Feedback Matters",
                  level: "h3",
                  color: "#1a202c",
                  alignment: "left",
                  font: "Georgia",
                  bold: true,
                  italic: false,
                  underline: false,
                },
              },
              {
                id: "column1-text",
                type: "text-block",
                data: {
                  content:
                    "Your insights help us understand what we're doing right and where we can improve. This directly impacts how we serve you better in the future.",
                  fontSize: "14px",
                  font: "Arial",
                  color: "#4a5568",
                  alignment: "left",
                  bold: false,
                  italic: false,
                  underline: false,
                },
              },
            ],
            [
              {
                id: "column2-image",
                type: "image",
                data: {
                  src: "https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg",
                  alt: "Customer service illustration",
                  width: "100%",
                  height: "auto",
                  pexelsQuery: "customer service",
                },
              },
            ],
          ],
          columnWidths: ["50.00%", "50.00%"],
        },
      },
      { id: "spacer-7", type: "spacer", data: { height: "40px" } },
      {
        id: "footer-social",
        type: "social-media",
        data: {
          platforms: [
            { name: "facebook", url: "YOUR_FACEBOOK_URL_HERE" },
            { name: "twitter", url: "YOUR_TWITTER_URL_HERE" },
            { name: "linkedin", url: "YOUR_LINKEDIN_URL_HERE" },
          ],
          iconSize: "24px",
          color: "#718096",
          alignment: "center",
        },
      },
      { id: "spacer-8", type: "spacer", data: { height: "20px" } },
      {
        id: "footer-text",
        type: "text-block",
        data: {
          content:
            "© 2023 [Your Company Name]. All rights reserved. | [Your Company Address]",
          fontSize: "12px",
          font: "Arial",
          color: "#718096",
          alignment: "center",
          bold: false,
          italic: false,
          underline: false,
        },
      },
      {
        id: "footer-unsubscribe",
        type: "text-block",
        data: {
          content:
            "You received this email because you are a valued customer. If you no longer wish to receive emails, you can <link>unsubscribe</link> here.",
          fontSize: "12px",
          font: "Arial",
          color: "#718096",
          alignment: "center",
          bold: false,
          italic: false,
          underline: false,
        },
      },
      {
        id: "footer-unsubscribe-link",
        type: "link",
        data: {
          text: "unsubscribe",
          url: "YOUR_UNSUBSCRIBE_LINK_HERE",
          color: "#3182ce",
          underline: true,
          alignment: "center",
        },
      },
    ],
  },
];
